# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: legalMicroservice.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17legalMicroservice.proto\"\x1e\n\tLocations\x12\x11\n\tlocations\x18\x01 \x03(\t\" \n\x0eLocationStatus\x12\x0e\n\x06status\x18\x01 \x03(\t\"\"\n\x0fLocationRequest\x12\x0f\n\x07request\x18\x01 \x03(\t\"\'\n\rLocationReply\x12\x16\n\x0e\x61vailLocations\x18\x01 \x03(\t2x\n\x11legalMicroservice\x12+\n\x0cgetLocations\x12\n.Locations\x1a\x0f.LocationStatus\x12\x36\n\x12\x61vailableLocations\x12\x10.LocationRequest\x1a\x0e.LocationReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'legalMicroservice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOCATIONS']._serialized_start=27
  _globals['_LOCATIONS']._serialized_end=57
  _globals['_LOCATIONSTATUS']._serialized_start=59
  _globals['_LOCATIONSTATUS']._serialized_end=91
  _globals['_LOCATIONREQUEST']._serialized_start=93
  _globals['_LOCATIONREQUEST']._serialized_end=127
  _globals['_LOCATIONREPLY']._serialized_start=129
  _globals['_LOCATIONREPLY']._serialized_end=168
  _globals['_LEGALMICROSERVICE']._serialized_start=170
  _globals['_LEGALMICROSERVICE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
