# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import legalMicroservice_pb2 as legalMicroservice__pb2


class legalMicroserviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLocations = channel.unary_unary(
                '/legalMicroservice/getLocations',
                request_serializer=legalMicroservice__pb2.Locations.SerializeToString,
                response_deserializer=legalMicroservice__pb2.LocationStatus.FromString,
                )
        self.availableLocations = channel.unary_unary(
                '/legalMicroservice/availableLocations',
                request_serializer=legalMicroservice__pb2.LocationRequest.SerializeToString,
                response_deserializer=legalMicroservice__pb2.LocationReply.FromString,
                )


class legalMicroserviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def availableLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_legalMicroserviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.getLocations,
                    request_deserializer=legalMicroservice__pb2.Locations.FromString,
                    response_serializer=legalMicroservice__pb2.LocationStatus.SerializeToString,
            ),
            'availableLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.availableLocations,
                    request_deserializer=legalMicroservice__pb2.LocationRequest.FromString,
                    response_serializer=legalMicroservice__pb2.LocationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'legalMicroservice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class legalMicroservice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/legalMicroservice/getLocations',
            legalMicroservice__pb2.Locations.SerializeToString,
            legalMicroservice__pb2.LocationStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def availableLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/legalMicroservice/availableLocations',
            legalMicroservice__pb2.LocationRequest.SerializeToString,
            legalMicroservice__pb2.LocationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
