# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proximityMicroservice.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproximityMicroservice.proto\x12\x0bproxPackage\"%\n\x0frankProxRequest\x12\x12\n\nrankPlease\x18\x01 \x01(\t\"S\n\x12rankedProxResponse\x12\x13\n\x0brankedAreas\x18\x01 \x01(\t\x12\x10\n\x08rankings\x18\x02 \x01(\x02\x12\x16\n\x0erankedResponse\x18\x03 \x01(\t2\xf7\x01\n\x08rankProx\x12M\n\ngetCommute\x12\x1c.proxPackage.rankProxRequest\x1a\x1f.proxPackage.rankedProxResponse\"\x00\x12K\n\x08getDrive\x12\x1c.proxPackage.rankProxRequest\x1a\x1f.proxPackage.rankedProxResponse\"\x00\x12O\n\x0cgetCommDrive\x12\x1c.proxPackage.rankProxRequest\x1a\x1f.proxPackage.rankedProxResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proximityMicroservice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RANKPROXREQUEST']._serialized_start=44
  _globals['_RANKPROXREQUEST']._serialized_end=81
  _globals['_RANKEDPROXRESPONSE']._serialized_start=83
  _globals['_RANKEDPROXRESPONSE']._serialized_end=166
  _globals['_RANKPROX']._serialized_start=169
  _globals['_RANKPROX']._serialized_end=416
# @@protoc_insertion_point(module_scope)
