# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proximityMicroservice_pb2 as proximityMicroservice__pb2


class rankProxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getCommute = channel.unary_unary(
                '/proxPackage.rankProx/getCommute',
                request_serializer=proximityMicroservice__pb2.rankProxRequest.SerializeToString,
                response_deserializer=proximityMicroservice__pb2.rankedProxResponse.FromString,
                )
        self.getDrive = channel.unary_unary(
                '/proxPackage.rankProx/getDrive',
                request_serializer=proximityMicroservice__pb2.rankProxRequest.SerializeToString,
                response_deserializer=proximityMicroservice__pb2.rankedProxResponse.FromString,
                )
        self.getCommDrive = channel.unary_unary(
                '/proxPackage.rankProx/getCommDrive',
                request_serializer=proximityMicroservice__pb2.rankProxRequest.SerializeToString,
                response_deserializer=proximityMicroservice__pb2.rankedProxResponse.FromString,
                )


class rankProxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getCommute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getDrive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCommDrive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_rankProxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getCommute': grpc.unary_unary_rpc_method_handler(
                    servicer.getCommute,
                    request_deserializer=proximityMicroservice__pb2.rankProxRequest.FromString,
                    response_serializer=proximityMicroservice__pb2.rankedProxResponse.SerializeToString,
            ),
            'getDrive': grpc.unary_unary_rpc_method_handler(
                    servicer.getDrive,
                    request_deserializer=proximityMicroservice__pb2.rankProxRequest.FromString,
                    response_serializer=proximityMicroservice__pb2.rankedProxResponse.SerializeToString,
            ),
            'getCommDrive': grpc.unary_unary_rpc_method_handler(
                    servicer.getCommDrive,
                    request_deserializer=proximityMicroservice__pb2.rankProxRequest.FromString,
                    response_serializer=proximityMicroservice__pb2.rankedProxResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proxPackage.rankProx', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class rankProx(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getCommute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proxPackage.rankProx/getCommute',
            proximityMicroservice__pb2.rankProxRequest.SerializeToString,
            proximityMicroservice__pb2.rankedProxResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getDrive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proxPackage.rankProx/getDrive',
            proximityMicroservice__pb2.rankProxRequest.SerializeToString,
            proximityMicroservice__pb2.rankedProxResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getCommDrive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proxPackage.rankProx/getCommDrive',
            proximityMicroservice__pb2.rankProxRequest.SerializeToString,
            proximityMicroservice__pb2.rankedProxResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
