# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: valueMS.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rvalueMS.proto\"\x1c\n\x07rankreq\x12\x11\n\tlocations\x18\x01 \x02(\t\"-\n\x07ranking\x12\x10\n\x08rankings\x18\x01 \x02(\t\x12\x10\n\x08response\x18\x02 \x02(\t2u\n\x11valueMicroservice\x12\x1e\n\x06getEnv\x12\x08.rankreq\x1a\x08.ranking\"\x00\x12\x1f\n\x07getWalk\x12\x08.rankreq\x1a\x08.ranking\"\x00\x12\x1f\n\x07getBoth\x12\x08.rankreq\x1a\x08.ranking\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'valueMS_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RANKREQ']._serialized_start=17
  _globals['_RANKREQ']._serialized_end=45
  _globals['_RANKING']._serialized_start=47
  _globals['_RANKING']._serialized_end=92
  _globals['_VALUEMICROSERVICE']._serialized_start=94
  _globals['_VALUEMICROSERVICE']._serialized_end=211
# @@protoc_insertion_point(module_scope)
